// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace CMGameplayTags
{
	#pragma region Input Tags
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_BaseAttack); // 삭제 예정
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_LockOn);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_Weapon);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip_Weapon);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);       // 삭제예정
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block); // 삭제예정
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Skill_Blade_Q);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Block);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Light);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Heavy);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Blade_Q);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Blade_E);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Blade_R);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Blade_F);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Arcanist_Q);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Arcanist_E);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Arcanist_R);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Arcanist_F);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Action_Interact);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);

	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickSlot_Utility);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickSlot_Potion);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Action_UseItem);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Action_CycleItem);
	
	#pragma endregion

	#pragma region UI Input Tags
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UI_Back);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UI_Inventory);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UI_Help);
	#pragma endregion
}