// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace CMGameplayTags
{
	#pragma region Foley Tags
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Handplant);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Jump);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Land);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Run);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_RunBackwds);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_RunStrafe);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Scuff);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_ScuffPivot);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_ScuffWall);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Tumble);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Walk);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_WalkBackwds);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Throw);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Immediate);
	#pragma endregion

	#pragma region Ability Tags
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Abilities_ContextualAnim);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Abilities_MoveTo);
	#pragma endregion

	#pragma region MotionMatching Tags
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Default);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Idle);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Loops);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Pivots);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Starts);
	CRIMSONMOON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Stops);
	#pragma endregion
}
